module.exports.action_bar = require('action_bar')
module.exports.chat_history = require('chat_history')
module.exports.tabs = require('tabs')
module.exports.graph_explorer = require('graph_explorer')
module.exports.tabbed_editor = require('tabbed_editor')
module.exports.search_bar = require('search_bar')
module.exports.manager = require('manager')
